# Generated by Django 3.0.8 on 2020-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_visit_date',
            field=models.CharField(max_length=100),
        ),
    ]
